/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.12.1/userguide/building_java_projects.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    application
    id("checkstyle")
}

checkstyle {
    config = resources.text.fromFile(file("${project.rootDir}"))
    toolVersion = "10.21.2"
}

tasks.register("checkstyle") {
    group = "verification"
    description = "Runs all Checkstyle tasks (main and test)."
    dependsOn("checkstyleMain", "checkstyleTest")
}
tasks.build {
    dependsOn("checkstyle")
}

repositories {
    mavenCentral()
}

dependencies {
    implementation(libs.guava)
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.11.4")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:5.11.4")
    testImplementation("org.assertj:assertj-core:3.27.3")
}

tasks.test {
    useJUnitPlatform()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    mainClass = "ru.job4j.Main"
}



